sulu_form.only:
    path: /form/only/{key}
    defaults: { _controller: SuluFormBundle:FormWebsite:only }

sulu_form.token:
    path: /form/token
    defaults: { _controller: SuluFormBundle:FormWebsite:token, _requestAnalyzer: false }
