l91_sulu_form.tests:
    type: rest
    resource: L91\Sulu\Bundle\FormBundle\Controller\ListController
    prefix: l91/form
    name_prefix: l91_sulu_form.

l91_sulu_form.dynamic:
    type: rest
    resource: L91\Sulu\Bundle\FormBundle\Controller\DynamicController
    prefix: l91/form
    name_prefix: l91_sulu_form.

l91.sulu.form.forms:
    type: rest
    resource: L91\Sulu\Bundle\FormBundle\Controller\FormController
    prefix: l91
    name_prefix: l91_sulu_form.

l91_sulu_form.csv_overlay:
    path: /form/templates/csv-export.html
    defaults:
        _controller: FrameworkBundle:Template:template
        template: L91SuluFormBundle:CsvExport:form.html.twig
